spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.21.168:8848

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'