spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.21.168:8848
server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        include: '*'
