spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.21.168:8848
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: localhost:8080
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true

